# Generated by Django 3.0.3 on 2021-03-29 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20210329_1744'),
        ('user_profile', '0002_auto_20210329_1823'),
    ]

    operations = [
    ]
