name: luna_backend
dependencies:
  - python=3.6
  - psycopg2=2.8
  - pip=21.0
  - pip:
      - django==3.0.3
      - djangorestframework==3.12.2
      - djangorestframework_simplejwt==4.4.0
      - pillow==8.1.2
      - drf_yasg==1.20.0
      - PyJWT==1.7.1
      - gunicorn==20.0.4
      - flake8==3.9