# Generated by Django 3.0.3 on 2021-03-29 18:23

from django.db import migrations, models
import restaurant.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=5)),
                ('website', models.URLField(max_length=250)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=250)),
                ('opening_hours', models.CharField(max_length=500)),
                ('price_level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1)),
                ('image', models.ImageField(upload_to=restaurant.models.user_directory_path)),
            ],
        ),
    ]
